### ISSUE TITLE
Adding Museums/Locations?

### ISSUE THREAD

**Issue by guidoschmidt** [terkelg/awesome-creative-coding#103]
How about adding a section with Museums or similar institutions that focus on generative art, creative coding related art and technology related artworks? In my region e.g., there's ZKM  in Karlsruhe. I'd be happy to open a PR

**Comment by madc** [comment]
+ Ars Electronica Center (Linz / AT)

**Comment by terkelg** [comment]
That's a great idea!

**Comment by guidoschmidt** [comment]
K, it's on PR #104
