### ISSUE TITLE
proposition of new links to add 

### ISSUE THREAD

**Issue by gregja** [terkelg/awesome-creative-coding#117]
Hi,
Thank's a lot for you great work.
I propose to you some new links to add, if you are interested :  

- OGL.js : new WebGL framework, minimal but powerful   
https://github.com/oframe/ogl  

- Zdog : a pseudo-3D engine for canvas & SVG (very funny to use, with an adorable design)
https://zzz.dog/

- jsdo.it-archives : an amazing compilation of experiments, by CX20, including comparisons between differents WebGL frameworks 
https://github.com/cx20/jsdo.it-archives

- a good WebGL Guide, by XEM
https://xem.github.io/articles/webgl-guide.html

- an excellent book, in french, on OpenGL, OpenGL ES and WebGL :
"Synthèse d'images avec OpenGL (ES)", by Pierre Nerzic, ed D-Booker (2017)
https://www.d-booker.fr/opengl/78-synthese-d-images.html

Best regards,
Greg

**Comment by terkelg** [comment]
Awesome links. I use OGL myself. Do you mind doing a PR for each of these links?

**Comment by gregja** [comment]
Ok, thank's. I'm preparing the PR, I will push it in few hours.
