### ISSUE TITLE
proposition to add a list of meetups dedicated to creative coders

### ISSUE THREAD

**Issue by gregja** [terkelg/awesome-creative-coding#119]
Hi,
Thank's a lot for merging my last PR.
For information, I'm co-organisor of a meetup in Paris, dedicated to creative coders : 

https://www.meetup.com/fr-FR/CreativeCodeParis/

And I know that there are some meetups like that in Berlin, and in London. 
If you're interested, I can start a list of those meetups.
Best regards

**Comment by terkelg** [comment]
That would be awesome – Happy to add it to the list
