### ISSUE TITLE
Replacing expired link

### ISSUE THREAD

**Issue by athossampayo** [terkelg/awesome-creative-coding#124]
Under **Quick References • Cheatsheets** the 

> Canvas Cheatsheet - Quick and visual canvas cheatsheet.

is expired, but it is still possible to get the web version of the CheatSheet on WaybackMachine:
https://web.archive.org/web/20171226205420/https://skilled.co/html-canvas/

It's possible to generate a PDF copy of this archive or, if you prefer, just remove the link.

**Comment by terkelg** [comment]
Thank you! I think a link to the archive could be good
