### ISSUE TITLE
Inquiry about Future Scope and Expansion of Creative Coding Repository

### ISSUE THREAD

**Issue by AideenHah-yil** [terkelg/awesome-creative-coding#187]
are there any emerging technologies or artistic practices that the repository plans to include in the future?

**Comment by ChenZiHong-Gavin** [comment]
same question

**Comment by terkelg** [comment]
Can you elaborate on what you have in mind?

**Comment by ChenZiHong-Gavin** [comment]
i will say https://artsandculture.google.com/

**Comment by terkelg** [comment]
If you want anything added to the list, feel free to create a PR
