### ISSUE TITLE
Suggestion establishing a career as a creative coder

### ISSUE THREAD

**Issue by dnecklesportfolio** [terkelg/awesome-creative-coding#25]
This isn't an issues but wasn't sure where to post the suggestion. I think this a great resource... being a creative coder is not in as high a job demand ( per keyword search  indeed ) than as a systems or engineer programmer. yet, I see many examples of creative coding on fwa and  Awwwards. Maybe we can include info or blog posts on the subject.

**Comment by terkelg** [comment]
Sure! I don't have the time to write it, but you're more than welcome to write something and submit a PR, than we can have a look at it.

**Comment by terkelg** [comment]
Hi @dnecklesportfolio. How are you?
Are you interested in doing a little writing about this?
