### ISSUE TITLE
Are people interested in a community forum?

### ISSUE THREAD

**Issue by terkelg** [terkelg/awesome-creative-coding#29]
Is this something people could find useful?
I bought the domain **creativecoding.rocks**, what should we do with it?

Let's be creative folks!

**Comment by jedahan** [comment]
make it an open source p5.js sketch that lets people write whatever in a big old stream, and contribute to different views?

turn it into a webring?

**Comment by madc** [comment]
@terkelg I always wanted to have a [hacker news](https://news.ycombinator.com/) like linklist for creative coding. Never found a useful open source implementation tough. I think it would go well with this list.

**Comment by terkelg** [comment]
That's a really good idea. Could be fun to build too

**Comment by skratchdot** [comment]
You could setup a https://github.com/discourse/discourse site.

**Comment by mgottholsen** [comment]
I'm into it.

**Comment by madc** [comment]
There are various discourse boards for creative coding related topics (i.e. [the oF forum](https://forum.openframeworks.cc/)). What I found interesting in the idea of having a "hacker news" for creative coding is its simplicity (even tough [hacker news ist not so simple](https://github.com/minimaxir/hacker-news-undocumented/blob/master/README.md)).

This kind of link list (what is the correct term?) also works, if there are only a few active users postings links..

**Comment by jedahan** [comment]
I like the idea of us making our own weird way to share cool links

**Comment by madc** [comment]
@terkelg Would you still offer your domain for such an endeavor? I'm proud co-owner of `creativecode.at`, so we could also use that one. Or go for something completely new. As a fourth option we could ask someone to sponsor the hosting and use a subdomain (i.e. `news.creativeapplications.net`).

**Comment by terkelg** [comment]
Sounds awesome guys. Let's build a link-sharing site for creative coding. Could be cool

**Comment by hangtwenty** [comment]
@terkelg Count me in. I'm currently overworked at work and eyes bleeding if I code extra, but I'm changing that imminently. I would love to help out with this project.

----

My prior related pursuits: I also have [an awesome list](https://github.com/hangtwenty/dive-into-machine-learning) that's in the [awesome list of awesome lists](https://github.com/sindresorhus/awesome) — howdy neighbor! Though I think yours is way more fun and brings together harder to find resources 😉 Also, a friend and I did [a workshop](https://github.com/hangtwenty/dadaconf-livecoding-guide) on a subset of this stuff... just a taster for some friends.

Soon, I want to start a meetup for such things here in Portland, OR, so I think it would be really cool to be involved in an online group too, and maybe get people mutually interested in these two things.

**Comment by hangtwenty** [comment]
@terkelg Maybe we can chat about eventually having meetup related features; MeetUp.com integration and/or a basic just-add-text version for the groups that don't use MeetUp.com

**Comment by hangtwenty** [comment]
Another thing, having a Slack (or Rocket Chat or any other clone like that) could be good for getting this off the ground.

**Comment by terkelg** [comment]
Hi @hangtwenty! First of all, you should make a PR with a link to your [dive-into-machine-learning](https://github.com/hangtwenty/) awesomelists if it's not already in the list.

**We can do this folks! Let's build a dope community site**. I totally agree with you @hangtwenty. We can start with something simple and then slowly customise and implement new features. It could be visual stuff (dribbble.com, cartrdge.com) or more community related stuff like ProductHunt/Indiehackers. I think **dev.to** is a cool example. We can have stuff like meet-ups, jobs etc.

**Comment by madc** [comment]
So, lets get some steam into this engine!

I've created a [GitHub Organization] (https://github.com/orgs/CreativeCodingRocks) and a [repo](https://github.com/CreativeCodingRocks/List).

If there are no objections, lets continue this discussion over here: https://github.com/CreativeCodingRocks/List/issues/1

**Comment by terkelg** [comment]
I know @hangtwenty is working on something already. We should touch base and maybe create a gitter char for this

**Comment by madc** [comment]
I added a link to it to the issue. @hangtwenty could you share your status over at the [List-repo](https://github.com/CreativeCodingRocks/List/issues/1)?

**Comment by hangtwenty** [comment]
@madc Hey just shared some thoughts. Sorry for the verbosity, I have some opinionated views but wanted to make sure I expressed them well! My core opinion is we need to be tight about scope to start, and pick some roles for getting started. But I don't want to stifle this awesome energy. I'm on the same page, want to keep the energy going! So I guess I used a lot of words to try and balance that 😆

**Comment by omarojo** [comment]
Joining the gitter :)

**Comment by terkelg** [comment]
This continues in Gitter and in the new [GitHub Organization](https://github.com/orgs/CreativeCodingRocks) and [repo](https://github.com/CreativeCodingRocks/List).
