### ISSUE TITLE
Would you accept a PR for a text generation section?

### ISSUE THREAD

**Issue by hangtwenty** [terkelg/awesome-creative-coding#43]
For things like [Rant](https://github.com/TheBerkin/rant) and more. I was about to make an awesome-list for this, and then decided probably better to contribute a sub-list here 😉

**Comment by terkelg** [comment]
Hi! Oh that's really cool! Can this go under the Ai/machine learning section?

**Comment by terkelg** [comment]
I would absolutely love a PR on this. Already sparked a few cool ideas - I can see a lot of creative use-cases for this

**Comment by hangtwenty** [comment]
Cool I'll send a PR very soon. Note to self:

- [ ] += [How to run a free Twitter Bot on AWS Lambda](https://dev.to/hivickylai/running-a-free-twitter-bot-on-aws-lambda--2pik) -- twitter bots are fun, and they are also just a good example of having a low-to-no-cost backend for procedural text generation, that fellow creative folks might not know about yet. _(Need to figure out how to phrase that concisely)_
