### ISSUE TITLE
dead site

### ISSUE THREAD

**Issue by rwebber** [terkelg/awesome-creative-coding#53]
blog section: abandonedart.org

**Comment by madc** [comment]
The last [Archive.org entry](https://web.archive.org/web/20180224033510/http://abandonedart.org/) says "Too many requests". Should we wait another month and take it out then?

**Comment by terkelg** [comment]
Thanks to both of you. Let's give it a few days

**Comment by thgie** [comment]
Seems to be an ad-list now.

**Comment by terkelg** [comment]
Yeah, it's removed in the latest commit 👍
