### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by StanLepunK** [terkelg/awesome-creative-coding#56]
Hello I'm not an expert for the PR with Github, I try a lot of time but fail every time :)
So before try again, if you look my project and think it can be interresting for your project : 
https://romanescoproject.wordpress.com/ and the github page is here : https://github.com/StanLepunK/ROMANESCO-Processing
I think that's can be on your way !

keep in touch if I must push something from Romanesco on your Github.

Stan le Punk

**Comment by terkelg** [comment]
Hi @StanLepunK. No worries!
Thanks for contributing. I'm not going to include these for now, but I've been thinking about making a section for people to share there personal code like this. 👍

**Comment by StanLepunK** [comment]
Hi @terkelg no problem, it was just information, because I thounght it's good place to talke about my project :) keep in touch.
