### ISSUE TITLE
Add Notch (www.notch.one)

### ISSUE THREAD

**Issue by guidoschmidt** [terkelg/awesome-creative-coding#66]
Haven't tried it myself yet, but [Notch](https://www.notch.one) seems so be a great software tool for realtime graphics and virtual reality. Seening really nice stuff get posted on Insta tagged with [#madewithnotch](https://www.instagram.com/explore/tags/madewithnotch/) recently.

**Comment by terkelg** [comment]
Interesting! Never heard about this tool before. I'll check it out for sure

**Comment by terkelg** [comment]
Ah it's windows only. Can't test it. I'm open to add this if you make a PR 👍
