### ISSUE TITLE
website link does not appear to work

### ISSUE THREAD

**Issue by rossbernet** [terkelg/awesome-creative-coding#92]
https://creativecoding.rocks

**Comment by terkelg** [comment]
Thank you! I'll have a look at it

**Comment by terkelg** [comment]
Domain expired – removing link 👍

**Comment by dym-sh** [comment]
so it was just a redirect domain to this repo?

**Comment by rossbernet** [comment]
It's still on the repo's description text:

![image](https://user-images.githubusercontent.com/8103418/63376078-f5cf7e80-c35a-11e9-84bf-82e326a2f08c.png)

**Comment by terkelg** [comment]
Thank you. @dym-sh yes the link was just a redirect. I never had the time to develop it
